version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          memory: 1g
  kibana:
    image: kibana:7.6.2
    ports:
      - 5601:5601
    deploy:
      resources:
        limits:
          memory: 1g
    depends_on:
      - elasticsearch
  fluent-bit:
    image: fluent/fluent-bit:latest
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    privileged: true
    ports:
      - 5170:5170
      - 2020:2020
    volumes:
      - ./conf/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./conf/parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/log:/fluent-bit/logs
    deploy:
      resources:
        limits:
          memory: 60m
    depends_on:
      - elasticsearch

